[package]
name = "arrow_util"
description = "Apache Arrow utilities"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ahash = { version = "0.8.0", default-features = false, features = ["runtime-rng"] }
# need dyn_cmp_dict feature for comparing dictionary arrays
arrow = { version = "25.0.0", features = ["prettyprint", "dyn_cmp_dict"] }
# used by arrow anyway (needed for printing workaround)
chrono = { version = "0.4", default-features = false }
comfy-table = { version = "6.1", default-features = false }
datafusion = { path = "../datafusion" }
hashbrown = "0.12"
num-traits = "0.2"
snafu = "0.7"
workspace-hack = { path = "../workspace-hack"}

[dev-dependencies]
arrow-flight = "25.0.0"
rand = "0.8.3"
